---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        host: web
        # port: 22
        timeout: 600
        delay: 1
        state: started
        validate_certs: false


    - name: "install python for Ansible."
      # Your code here
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
    # Add more env vars here

    - roles:
      - name: "update apt packages"
        become: true
        apt:
          update_cache: yes

      - name: "upgrade packages"
        become: true
        apt:
          upgrade: yes

      - name: "Remove some dependences that are not required"
        become: true
        apt:
          autoremove: yes

      - name: "Install Node.js and NPM"
        apt:
          name:
            - "nodejs"
            - "npm"
          state: latest
          update_cache: yes

      - name: "Install pm2"
        become: true
        npm:
          name: pm2
          global: yes
          production: yes
          state: latest

    # - name: "creates directory"
    #   file:
    #     path: ~/web
    #     state: directory

    # - name: "copy index text page"
    #   template:
    #     src: files/index.js
    #     dest: ~/web/index.js

    # - name: "executing node"
    #   shell:  pm2 start ~/web/index.js -f



