
- name: "update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Remove some dependences that are not required"
  become: true
  apt:
    autoremove: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
    
- name: "Install NPM"
  apt:
    name:
      - "npm"
    state: present
    update_cache: yes

- name: "install n"
  become: true
  npm:
    name: n
    global: yes
    production: yes

# - name: "Extract backend into remote directory"
#   ansible.builtin.unarchive:
#     src: artifact.tar.gz
#     dest: ~/
#     remote_src: true

    # pm2 stop default
    # pm2 start npm -- start
