- name: "install node exporter."
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

# Eze Code
- name: "move binary to /usr/local/bin."
  become: true
  become_user: root
  become_method: sudo
  get_url:
    url:
      - wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      - tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
      - cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
      - rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: "enable node_exporter service"
  become: true
  become_user: root
  become_method: sudo
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter
# Eze Code

# - name: "enable node_exporter service"
#   become: true
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: node_exporter
#     enabled: yes

# - global:
#     scrape_interval: 15s
#     external_labels:
#       monitor: 'prometheus'

# - scrape_configs:
#     - job_name: 'prometheus'
#       static_configs:
#         - targets: ['localhost:9090']

#     - job_name: 'node_exporter'
#       static_configs:
#         - targets: ['localhost:9100']

    # - job_name: 'node'
    #   ec2_sd_configs:
    #     - region: 'us-east-1'
    #       access_key: 'AKIA3QQ4X5D2OSKJ5YWV'
    #       secret_key: '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'
    #       port: 9100