

- name: "install alert manager."
  become: true
  shell: |
    wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz


- name: "move binary to /usr/local/bin."
  become: true
  become_user: root
  become_method: sudo
  shell: |
    mv alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin
    mv alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
    mkdir /var/lib/alertmanager
    rm -rf alertmanager*

- name: "add alert manager configuration"
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service


- name: "add alert manager alertmanager configuration"
  become: true
  copy:
    src: alertmanager.yml
    dest: /etc/prometheus/alertmanager.yml


- name: "add rules configuration to prometheus"
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/rules.yml


- name: "enable alert manager service"
  become: true
  become_user: root
  become_method: sudo
  shell: |
    systemctl daemon-reload
    systemctl enable alertmanager
    systemctl start alertmanager
